update code

diff --git a/.github/workflows/guide-docs.yml b/.github/workflows/guide-docs.yml
--- a/.github/workflows/guide-docs.yml
+++ b/.github/workflows/guide-docs.yml
@@ -40,22 +40,22 @@ jobs:
         id: detect-package-manager
         working-directory: ./apps/docs
         run: |
-          # if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-          #   echo "manager=yarn" >> $GITHUB_OUTPUT
-          #   echo "command=install" >> $GITHUB_OUTPUT
-          #   exit 0
-          # elif [ -f "${{ github.workspace }}/package.json" ]; then
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
             echo "manager=npm" >> $GITHUB_OUTPUT
             echo "command=ci" >> $GITHUB_OUTPUT
-          #   exit 0
-          # else
-          #   echo "Unable to determine package manager"
-          #   exit 1
-          # fi
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: '14'
           cache: ${{ steps.detect-package-manager.outputs.manager }}
           cache-dependency-path: ./apps/docs/package-lock.json
       - name: Setup Pages
@@ -80,14 +80,14 @@ jobs:
         run: npm config set registry https://npm.shlab.tech/
 
       - name: Install dependencies
-        run: npm install
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
         working-directory: ./apps/docs
 
       - name: Build with Gatsby
         working-directory: ./apps/docs
         env:
           PREFIX_PATHS: 'true'
-        run: npm run build
+        run: ${{ steps.detect-package-manager.outputs.manager }} run build
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v2
         with:
